export type Brand = {
  id: string;
  name: string;
  /** Path to logo in /public. Empty string = show initial fallback. */
  logo: string;
};

export const establishedBrands: Brand[] = [
  { id: "nike", name: "Nike", logo: "/images/brands/nike.svg" },
  { id: "adidas", name: "Adidas", logo: "/images/brands/adidas.svg" },
  { id: "gucci", name: "Gucci", logo: "/images/brands/gucci.png" },
  { id: "louisvuitton", name: "Louis Vuitton", logo: "/images/brands/louisvuitton.png" },
  { id: "prada", name: "Prada", logo: "/images/brands/prada.png" },
  { id: "burberry", name: "Burberry", logo: "/images/brands/burberry.png" },
  { id: "calvinklein", name: "Calvin Klein", logo: "/images/brands/calvinklein.png" },
  { id: "tommyhilfiger", name: "Tommy Hilfiger", logo: "/images/brands/tommyhilfiger.png" },
  { id: "ralphlauren", name: "Ralph Lauren", logo: "/images/brands/ralphlauren.png" },
  { id: "coach", name: "Coach", logo: "/images/brands/coach.png" },
  { id: "hm", name: "H&M", logo: "/images/brands/hm.svg" },
  { id: "zara", name: "Zara", logo: "/images/brands/zara.svg" },
  { id: "asos", name: "ASOS", logo: "/images/brands/asos.png" },
  { id: "levis", name: "Levi's", logo: "/images/brands/levis.png" },
  { id: "versace", name: "Versace", logo: "/images/brands/versace.png" },
  { id: "loreal", name: "L'Oréal", logo: "/images/brands/loreal.png" },
  { id: "mac", name: "MAC Cosmetics", logo: "/images/brands/mac.png" },
  { id: "sephora", name: "Sephora", logo: "/images/brands/sephora.png" },
  { id: "charlottetilbury", name: "Charlotte Tilbury", logo: "/images/brands/charlottetilbury.png" },
  { id: "nars", name: "NARS", logo: "/images/brands/nars.png" },
  { id: "dior", name: "Dior", logo: "/images/brands/dior.svg" },
  { id: "fentybeauty", name: "Fenty Beauty", logo: "/images/brands/fentybeauty.png" },
  { id: "urbandecay", name: "Urban Decay", logo: "/images/brands/urbandecay.png" },
  { id: "neutrogena", name: "Neutrogena", logo: "/images/brands/neutrogena.png" },
  { id: "olay", name: "Olay", logo: "/images/brands/olay.png" },
  { id: "dove", name: "Dove", logo: "/images/brands/dove.png" },
  { id: "cerave", name: "CeraVe", logo: "/images/brands/cerave.png" },
  { id: "cetaphil", name: "Cetaphil", logo: "/images/brands/cetaphil.png" },
  { id: "cocacola", name: "Coca-Cola", logo: "/images/brands/cocacola.svg" },
  { id: "pepsi", name: "Pepsi", logo: "/images/brands/pepsi.png" },
  { id: "redbull", name: "Red Bull", logo: "/images/brands/redbull.svg" },
  { id: "starbucks", name: "Starbucks", logo: "/images/brands/starbucks.svg" },
  { id: "lululemon", name: "Lululemon", logo: "/images/brands/lululemon.png" },
  { id: "underarmour", name: "Under Armour", logo: "/images/brands/underarmour.svg" },
  { id: "reebok", name: "Reebok", logo: "/images/brands/reebok.svg" },
  { id: "puma", name: "Puma", logo: "/images/brands/puma.svg" },
  { id: "pantene", name: "Pantene", logo: "/images/brands/pantene.png" },
  { id: "clinique", name: "Clinique", logo: "/images/brands/clinique.png" },
  { id: "esteelauder", name: "Estée Lauder", logo: "/images/brands/esteelauder.png" },
  { id: "maisonmargiela", name: "Maison Margiela", logo: "/images/brands/maisonmargiela.png" },
];

export const emergingBrands: Brand[] = [
  { id: "rarebeauty", name: "Rare Beauty", logo: "/images/brands/rarebeauty.png" },
  { id: "iliabeauty", name: "ILIA Beauty", logo: "/images/brands/iliabeauty.png" },
  { id: "meritbeauty", name: "Merit Beauty", logo: "/images/brands/meritbeauty.png" },
  { id: "jonesroad", name: "Jones Road", logo: "/images/brands/jonesroad.png" },
  { id: "westmanatelier", name: "Westman Atelier", logo: "/images/brands/westmanatelier.png" },
  { id: "amicole", name: "Ami Colé", logo: "/images/brands/amicole.png" },
  { id: "glossier", name: "Glossier", logo: "/images/brands/glossier.png" },
  { id: "skims", name: "SKIMS", logo: "/images/brands/skims.png" },
  { id: "parade", name: "Parade", logo: "/images/brands/parade.png" },
  { id: "girlfriendcollective", name: "Girlfriend Collective", logo: "/images/brands/girlfriendcollective.png" },
  { id: "allbirds", name: "Allbirds", logo: "/images/brands/allbirds.png" },
  { id: "veja", name: "Veja", logo: "/images/brands/veja.png" },
  { id: "reformation", name: "Reformation", logo: "/images/brands/reformation.png" },
  { id: "christydawn", name: "Christy Dawn", logo: "/images/brands/christydawn.png" },
  { id: "patagonia", name: "Patagonia", logo: "/images/brands/patagonia.png" },
  { id: "olipop", name: "Olipop", logo: "/images/brands/olipop.png" },
  { id: "poppi", name: "Poppi", logo: "/images/brands/poppi.png" },
  { id: "liquiddeath", name: "Liquid Death", logo: "/images/brands/liquiddeath.png" },
  { id: "nixie", name: "Nixie", logo: "/images/brands/nixie.png" },
  { id: "delacalle", name: "De La Calle", logo: "/images/brands/delacalle.png" },
  { id: "seedhealth", name: "Seed Health", logo: "/images/brands/seedhealth.png" },
  { id: "ag1", name: "AG1", logo: "/images/brands/ag1.png" },
  { id: "ritual", name: "Ritual", logo: "/images/brands/ritual.png" },
  { id: "humnutrition", name: "HUM Nutrition", logo: "/images/brands/humnutrition.png" },
  { id: "beam", name: "Beam", logo: "/images/brands/beam.png" },
  { id: "momentous", name: "Momentous", logo: "/images/brands/momentous.png" },
  { id: "lmnt", name: "LMNT", logo: "/images/brands/lmnt.png" },
  { id: "nuun", name: "Nuun", logo: "/images/brands/nuun.png" },
  { id: "koparibeauty", name: "Kopari Beauty", logo: "/images/brands/koparibeauty.png" },
  { id: "youthtothepeopletwo", name: "Youth to the People", logo: "/images/brands/youththepeoplepeople.png" },
  { id: "herbivore", name: "Herbivore", logo: "/images/brands/herbivore.png" },
  { id: "versed", name: "Versed", logo: "/images/brands/versed.png" },
  { id: "byoma", name: "Byoma", logo: "/images/brands/byoma.png" },
  { id: "kosas", name: "Kosas", logo: "/images/brands/kosas.png" },
  { id: "tower28", name: "Tower 28", logo: "/images/brands/tower28.png" },
  { id: "topicals", name: "Topicals", logo: "/images/brands/topicals.png" },
  { id: "moonjuice", name: "Moon Juice", logo: "/images/brands/moonjuice.png" },
  { id: "hellobello", name: "Hello Bello", logo: "/images/brands/hellobello.png" },
  { id: "forloveandlemons", name: "For Love & Lemons", logo: "/images/brands/forloveandlemons.png" },
  { id: "culturekingnah", name: "Culture Kings", logo: "/images/brands/culturekings.png" },
];
